name: nightly
on:
  push:
  pull_request:
  schedule:
    - cron: '49 04 * * 0,3'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  container-tests:
    strategy:
      fail-fast: false
      matrix:
          conf:
            - bld: -DAPPEND_CXXFLAGS="-O3 -g2"       -DAPPEND_CFLAGS='-O3 -g2'       -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="clang-${LLVM_VERSION}" -DCMAKE_CXX_COMPILER="clang++-${LLVM_VERSION};-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG" -DSANITIZERS=thread -DBUILD_GUI=OFF   -DCMAKE_CXX_FLAGS="-O3 -g2 ${LIBCXX_FLAGS} -pthread -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG"   -DCMAKE_C_FLAGS="-O3 -g2 -pthread" 

              build_instrumented_libcxx: true
              task_adjustments: ''
              desc: "libc++ DEBUG tsan"
              test: fun,fuzz
              os: ubuntu-24.04

            - bld: -DAPPEND_CXXFLAGS='-O3 -g2'       -DAPPEND_CFLAGS='-O3 -g2'       -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="clang-${LLVM_VERSION}" -DCMAKE_CXX_COMPILER="clang++-${LLVM_VERSION}" -DSANITIZERS=thread -DBUILD_GUI=OFF
              task_adjustments: |
                sed -i '/threadpool_tests\.cpp/d' src/test/CMakeLists.txt
              desc: "clang tsan"
              test: fun
              os: ubuntu-24.04

            - bld: -DAPPEND_CXXFLAGS='-O3 -g2'       -DAPPEND_CFLAGS='-O3 -g2'       -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="/opt/gcc-latest/bin/gcc" -DCMAKE_CXX_COMPILER="/opt/gcc-latest/bin/g++;-static-libstdc++" -DSANITIZERS=thread -DBUILD_GUI=OFF -DAPPEND_CXXFLAGS="-O3 -g2 -Wno-error=stringop-overflow -Wno-error=maybe-uninitialized -Wno-error=array-bounds"
              task_adjustments: |
                sed -i '/threadpool_tests\.cpp/d' src/test/CMakeLists.txt
                dnf install -y libtsan
                echo 'race:libQt6Core' >> test/sanitizer_suppressions/tsan
                echo 'race:libQt6Test' >> test/sanitizer_suppressions/tsan
              desc: "g++ tsan"
              test: fun
              os: ubuntu-24.04

            - bld: -DAPPEND_CXXFLAGS='-O3 -g2'       -DAPPEND_CFLAGS='-O3 -g2'       -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="clang-${LLVM_VERSION}" -DCMAKE_CXX_COMPILER="clang++-${LLVM_VERSION};-stdlib=libc++;-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG" -DBUILD_GUI=OFF
              task_adjustments: ''
              desc: "libc++ DEBUG ARM"
              test: fun,fuzz
              os: ubuntu-24.04-arm

            - bld: -DAPPEND_CXXFLAGS='-O3 -g2'       -DAPPEND_CFLAGS='-O3 -g2'       -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="clang-${LLVM_VERSION}" -DCMAKE_CXX_COMPILER="clang++-${LLVM_VERSION};-stdlib=libc++;-funsigned-char" -DSANITIZERS=address,float-divide-by-zero,integer,undefined -DBUILD_GUI=OFF
              task_adjustments: ''
              desc: "libc++ asan -funsigned-char"
              test: fun,fuzz
              os: ubuntu-24.04

            - bld: -DAPPEND_CXXFLAGS='-O3 -g2'       -DAPPEND_CFLAGS='-O3 -g2'       -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="clang-${LLVM_VERSION}" -DCMAKE_CXX_COMPILER="clang++-${LLVM_VERSION};-funsigned-char" -DSANITIZERS=address,float-divide-by-zero,integer,undefined -DBUILD_GUI=ON
              task_adjustments: ''
              desc: "clang asan -funsigned-char + gui"
              test: fun
              os: ubuntu-24.04

            - bld: -DAPPEND_CXXFLAGS='-O3 -g2'       -DAPPEND_CFLAGS='-O3 -g2'       -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="/opt/gcc-latest/bin/gcc" -DCMAKE_CXX_COMPILER="/opt/gcc-latest/bin/g++;-static-libstdc++" -DSANITIZERS=address,undefined -DBUILD_GUI=OFF -DAPPEND_CXXFLAGS="-O3 -g2 -Wno-error=maybe-uninitialized -Wno-error=array-bounds"
              task_adjustments: |
                dnf install -y libasan libubsan
                echo 'nonnull-attribute:streams.h' >> test/sanitizer_suppressions/ubsan
                echo 'nonnull-attribute:streams.cpp' >> test/sanitizer_suppressions/ubsan
              desc: "g++ asan + gui(temp_disabled)"
              test: fun,fuzz
              os: ubuntu-24.04

            - bld: -DAPPEND_CXXFLAGS='-O3 -g2 -flto' -DAPPEND_CFLAGS='-O3 -g2 -flto' -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="clang-${LLVM_VERSION}" -DCMAKE_CXX_COMPILER="clang++-${LLVM_VERSION};-stdlib=libc++" -DAPPEND_LDFLAGS="-flto" -DBUILD_GUI=OFF
              task_adjustments: ''
              desc: "libc++ lto"
              test: fun,fuzz
              os: ubuntu-24.04

            - bld:                                 -DAPPEND_CFLAGS='-O3 -g2    ' -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="/opt/gcc-latest/bin/gcc" -DCMAKE_CXX_COMPILER="/opt/gcc-latest/bin/g++;-static-libstdc++;-D_GLIBCXX_DEBUG;-D_GLIBCXX_DEBUG_PEDANTIC" -DAPPEND_CXXFLAGS="-O3 -g2    -Wno-error=array-bounds -Wno-error=stringop-overflow"
              task_adjustments: ''
              desc: "g++ DEBUG no_lto"
              test: fun,fuzz
              os: ubuntu-24.04

            - bld:                                 -DAPPEND_CFLAGS='-O3 -g2    ' -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="/opt/gcc-latest/bin/gcc" -DCMAKE_CXX_COMPILER="/opt/gcc-latest/bin/g++;-static-libstdc++" -DBUILD_GUI=ON -DAPPEND_CXXFLAGS="-O3 -g2    -Wno-error=array-bounds -Wno-error=stringop-overflow"
              task_adjustments: ''
              desc: "g++ no_lto"
              test: fun,fuzz
              os: ubuntu-24.04

            - bld: -DAPPEND_CXXFLAGS='-O3 -g2'       -DAPPEND_CFLAGS='-O3 -g2'       -DCMAKE_BUILD_TYPE=Debug -DAPPEND_CPPFLAGS='-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES' -DCMAKE_C_COMPILER="clang-${LLVM_VERSION}" -DCMAKE_CXX_COMPILER="clang++-${LLVM_VERSION};-stdlib=libstdc++"
              task_adjustments: ''
              desc: "clang libstdc++ ARM"
              test: fun,fuzz
              os: ubuntu-24.04-arm

    name: '${{ matrix.conf.desc }} ${{ matrix.conf.test }}'
    runs-on: ${{ matrix.conf.os }}
    timeout-minutes: 360
    container:
      image: ${{ contains(matrix.conf.bld, 'gcc-latest') && 'fedora:latest' || 'ubuntu:24.04' }}

    steps:
      - &CHECKOUT_BC
        name: Checkout Bitcoin Core repo
        uses: actions/checkout@v5
        with:
          repository: bitcoin/bitcoin
          fetch-depth: 1

      - name: Set sanitizer suppressions (only for ctest+functional)
        run: |
          echo LSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/lsan" >> "$GITHUB_ENV"
          echo TSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/tsan:halt_on_error=1:second_deadlock_stack=1" >> "$GITHUB_ENV"
          echo UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1:report_error_type=1" >> "$GITHUB_ENV"

      - name: Install clang (Ubuntu)
        if: "!contains(matrix.conf.bld, 'gcc-latest')"
        run: |
          apt-get update && apt-get install -y software-properties-common curl
          curl "https://apt.llvm.org/llvm-snapshot.gpg.key" | apt-key add -
          . /etc/os-release
          REPO="deb http://apt.llvm.org/${VERSION_CODENAME} llvm-toolchain-${VERSION_CODENAME} main"
          add-apt-repository -y "${REPO}"
          apt-get update
          LLVM_VERSION=$( apt-cache search --names-only '^clang-[0-9]+$' | sort --version-sort | tail -1 | cut -f1 -d" " | cut -f2 -d"-" )
          echo "LLVM_VERSION=${LLVM_VERSION}" >> "$GITHUB_ENV"
          echo "LLVM_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-${LLVM_VERSION}" >> "$GITHUB_ENV"
          apt-get install -y clang-${LLVM_VERSION} llvm-${LLVM_VERSION} llvm-${LLVM_VERSION}-dev libclang-${LLVM_VERSION}-dev libclang-rt-${LLVM_VERSION}-dev libc++-${LLVM_VERSION}-dev libc++abi-${LLVM_VERSION}-dev git cmake pkg-config build-essential ninja-build libboost-dev libsqlite3-dev libcapnp-dev capnproto libzmq3-dev ccache qt6-tools-dev qt6-l10n-tools qt6-base-dev libqrencode-dev systemtap-sdt-dev python3-zmq
          echo
          clang-${LLVM_VERSION} -v

      - name: Build instrumented libc++
        if: ${{ matrix.conf.build_instrumented_libcxx }}
        run: |
          git clone --depth=1 https://github.com/llvm/llvm-project /llvm-project
          cmake -G Ninja -B /cxx_build/ \
            -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_USE_SANITIZER="Thread" \
            -DCMAKE_C_COMPILER=clang-${LLVM_VERSION} \
            -DCMAKE_CXX_COMPILER=clang++-${LLVM_VERSION} \
            -DLLVM_TARGETS_TO_BUILD=Native \
            -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF \
            -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
            -DLIBCXX_ABI_DEFINES="_LIBCPP_ABI_BOUNDED_ITERATORS;_LIBCPP_ABI_BOUNDED_ITERATORS_IN_STD_ARRAY;_LIBCPP_ABI_BOUNDED_ITERATORS_IN_STRING;_LIBCPP_ABI_BOUNDED_ITERATORS_IN_VECTOR;_LIBCPP_ABI_BOUNDED_UNIQUE_PTR" \
            -DLIBCXX_HARDENING_MODE=debug \
            -S /llvm-project/runtimes
          ninja -C /cxx_build/ -j "$(nproc)"
          echo "LIBCXX_DIR=/cxx_build/" >> "$GITHUB_ENV"
          echo 'LIBCXX_FLAGS=-fsanitize=thread -nostdinc++ -nostdlib++ -isystem /cxx_build/include/c++/v1 -L/cxx_build/lib -Wl,-rpath,/cxx_build/lib -lc++ -lc++abi -lpthread -Wno-unused-command-line-argument' >> "$GITHUB_ENV"
          du -sh /llvm-project
          rm -rf /llvm-project

      - name: Install gcc (Fedora)
        if: "contains(matrix.conf.bld, 'gcc-latest')"
        run: |
          dnf install -y git cmake pkgconfig boost-devel sqlite-devel capnproto capnproto-devel zeromq-devel ccache qt6-qttools-devel qt6-qtbase-devel qrencode-devel systemtap-sdt-devel python3-zmq libstdc++
          dnf -y copr enable jwakely/gcc-latest
          dnf -y install gcc-latest
          echo
          /opt/gcc-latest/bin/g++ --version

      - name: Apply matrix adjustments
        if: ${{ matrix.conf.task_adjustments != '' }}
        run: |
          ${{ matrix.conf.task_adjustments }}

      - name: Generate buildsystem
        run: >
          cmake -B bld \
            ${{ matrix.conf.bld }} \
            --preset=dev-mode \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - &BLD
        name: Build
        run: cmake --build ./bld -j $(nproc)

      - name: Clean up temporary build files
        # Needed for GHA CI runners with limited storage space
        run: |
          BUILD_DIR="./bld"
          du -sh "${BUILD_DIR}"
          find "${BUILD_DIR}" -type d -name CMakeFiles -exec rm -rf {} +
          du -sh "${BUILD_DIR}"

      - name: Run tests (ctest+functional)
        if: contains(matrix.conf.test, 'fun')
        run: &TESTS_RUN |
          ctest --output-on-failure --stop-on-failure --test-dir ./bld -j $(nproc)
          ./bld/test/functional/test_runner.py -j $(( $(nproc) * 2 )) --combinedlogslen=99999999 --timeout-factor=10 --extended --exclude "interface_bitcoin_cli" --exclude "rpc_bind --ipv6"

      - name: Run tests (fuzz)
        if: contains(matrix.conf.test, 'fuzz')
        run: |
          git clone https://github.com/bitcoin-core/qa-assets --depth=1
          ./bld/test/fuzz/test_runner.py -l DEBUG -j $(nproc) ./qa-assets/fuzz_corpora/

  ci-mutation-matrix:
    #
    # Allows running on self-hosted runners via qemu-user.
    #
    # * Due to bugs in qemu-s390x, at least qemu-user 9.x+ is required, meaning
    #   RHEL-based 9 only (RHEL-10+, Debian 13+, or Ubuntu 26.04+ do not work?).
    # * On machines that are persisted between CI jobs,
    #   RESTART_CI_DOCKER_BEFORE_RUN=1 ensures that previous containers and
    #   artifacts are cleared before each run. This requires installing Podman
    #   instead of Docker.
    # * Install and setup the ./ci/ dependencies, along with swap (to avoid
    #   rare and intermittent OOM due to short memory usage spikes), a shared
    #   ccache (only needed for multi-user/multi-runner systems, needs the env
    #   vars "CCACHE_MAXSIZE=100G DANGER_CI_ON_HOST_CCACHE_FOLDER=1
    #   CCACHE_UMASK=000 CCACHE_DIR=/ci_ccache_shared" later on), and user
    #   login key mangament:
    #
    # ```
    # # Ubuntu/Debian
    # fallocate -l 16G /swapfile_ci && chmod 600 /swapfile_ci && mkswap /swapfile_ci && swapon /swapfile_ci && ( echo '/swapfile_ci none swap sw 0 0' | tee -a /etc/fstab ) && apt update    && apt upgrade -y             &&  apt install -y git screen python3 bash podman-docker uidmap slirp4netns passt aardvark-dns curl                    && podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes && sysctl vm.mmap_rnd_bits=28 && mkdir -p /ci_ccache_shared && chmod 2777 /ci_ccache_shared/ && ssh-keygen -t ed25519 -f "$HOME/.ssh/id_ci_workers" -N "" && ssh dummy@localhost
    #
    # # RHEL-based (only work on 9.x?)
    # fallocate -l 16G /swapfile_ci && chmod 600 /swapfile_ci && mkswap /swapfile_ci && swapon /swapfile_ci && ( echo '/swapfile_ci none swap sw 0 0' | tee -a /etc/fstab ) && dnf update -y && dnf install epel-release -y && dnf install -y git screen python3 bash podman-docker shadow-utils-subid slirp4netns passt aardvark-dns curl libicu && podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes && sysctl vm.mmap_rnd_bits=28 && mkdir -p /ci_ccache_shared && chmod 2777 /ci_ccache_shared/ && ssh-keygen -t ed25519 -f "$HOME/.ssh/id_ci_workers" -N "" && ssh dummy@localhost
    # ```
    #
    # * To register the persistent worker, open a `screen` session, before getting a token from https://github.com/maflcko/bitcoin-core-nightly/settings/actions/runners/new :
    #
    # ```
    # ( export CI_W_NAME="ci_worker_$( date +%s_%N )" && groupadd --force ci_ccache_share && useradd --create-home --user-group --groups ci_ccache_share "${CI_W_NAME}" && ( cat "$HOME/.ssh/id_ci_workers.pub" | su - "${CI_W_NAME}" -c 'mkdir -p ~/.ssh && ( cat >> ~/.ssh/authorized_keys ) && chmod -R go= ~/.ssh ' ) && screen -S "session_${CI_W_NAME}" ssh -i "$HOME/.ssh/id_ci_workers" "${CI_W_NAME}@localhost" 'RESTART_CI_DOCKER_BEFORE_RUN=1 bash -c "mkdir actions-runner && cd actions-runner && curl -o actions-runner-linux-x64.tar.gz -L https://github.com/actions/runner/releases/download/v2.334.0/actions-runner-linux-x64-2.334.0.tar.gz && tar xzf ./actions-runner-linux-x64.tar.gz && ./config.sh --labels runner_test_001 --name $USER --unattended --url https://github.com/maflcko/bitcoin-core-nightly --token _token_ && ./run.sh  " ' )
    # ```
    #
    # Warning: The mutation matrix below will likely lead to cache-thrashing, because the CI container name is not adjusted for matrix mutations.

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner || 'ubuntu-latest' }}
    timeout-minutes: 360

    env:
      CI_FAILFAST_TEST_LEAVE_DANGLING: 1  # GHA does not care about dangling processes and setting this variable avoids killing the CI script itself on error
      FILE_ENV: ${{ matrix.file-env }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'msan ext -O0'
            file-env: './ci/test/00_setup_env_native_msan.sh'
            task_adjustments: |
              sed -i 's/-O1/-O0/g' $FILE_ENV
              sed -i '/^export CI_LIMIT_STACK_SIZE=1$/d' $FILE_ENV
              echo 'TEST_RUNNER_TIMEOUT_FACTOR=400' >> $GITHUB_ENV
              echo 'TEST_RUNNER_EXTRA="--extended"' >> $FILE_ENV
          - name: 'fuzz msan -O0'
            file-env: './ci/test/00_setup_env_native_fuzz_with_msan.sh'
            task_adjustments: |
              sed -i 's/-O1/-O0/g' $FILE_ENV
          - name: 'asan ext -O0'
            file-env: './ci/test/00_setup_env_native_asan.sh'
            task_adjustments: |
              sed -i "s/-DAPPEND_CXXFLAGS='/-DAPPEND_CXXFLAGS='-O0 -g2 /g" $FILE_ENV
              sed -i '/^export CI_LIMIT_STACK_SIZE=1$/d' $FILE_ENV
              echo 'TEST_RUNNER_TIMEOUT_FACTOR=400' >> $GITHUB_ENV
              echo 'TEST_RUNNER_EXTRA="--extended"' >> $FILE_ENV
          - name: 'fuzz asan -O0'
            file-env: './ci/test/00_setup_env_native_fuzz.sh'
            task_adjustments: |
              sed -i "s/-DSANITIZERS=/-DAPPEND_CXXFLAGS='-O0 -g2' -DSANITIZERS=/g" $FILE_ENV
          - name: 'tsan ext -O0'
            file-env: './ci/test/00_setup_env_native_tsan.sh'
            task_adjustments: |
              sed -i "s/-DSANITIZERS=/-DAPPEND_CXXFLAGS='-O0 -g2' -DSANITIZERS=/g" $FILE_ENV
              sed -i '/^export CI_LIMIT_STACK_SIZE=1$/d' $FILE_ENV
              echo 'TEST_RUNNER_TIMEOUT_FACTOR=400' >> $GITHUB_ENV
              echo 'TEST_RUNNER_EXTRA="--extended"' >> $FILE_ENV
          - name: 'fuzz tsan'
            file-env: './ci/test/00_setup_env_native_fuzz.sh'
            task_adjustments: |
              sed -i --regexp-extended 's/fuzzer,address\S*/fuzzer,thread/g' $FILE_ENV
          - name: 'fuzz i386'
            file-env: './ci/test/00_setup_env_native_fuzz.sh'
            task_adjustments: |
              sed -i 's/ubuntu:26.04/debian:unstable/g' $FILE_ENV
              sed -i '/export APT_LLVM_V=".."/d' $FILE_ENV
              sed -i 's/-${APT_LLVM_V}//g' $FILE_ENV
              sed -i "s/-DCMAKE_CXX_FLAGS='/-DAPPEND_LDFLAGS='-latomic' -DCMAKE_CXX_FLAGS='/g" $FILE_ENV
              echo 'export CI_IMAGE_PLATFORM="linux/i386"' >> $FILE_ENV
              echo 'implicit-signed-integer-truncation:MillisToTimeval' >> test/sanitizer_suppressions/ubsan  # Shold be fixed on armhf. For i386 could append -D_TIME_BITS=64 in CMakeLists.txt
              echo 'implicit-signed-integer-truncation:streams.cpp' >> test/sanitizer_suppressions/ubsan  # Use fseeko/ftello (POSIX, uses off_t) on platforms where available. CMakeLists.txt:    _FILE_OFFSET_BITS=64 is already set
              echo 'implicit-unsigned-integer-truncation:util/hasher.h' >> test/sanitizer_suppressions/ubsan
              echo 'implicit-unsigned-integer-truncation:util/hasher.cpp' >> test/sanitizer_suppressions/ubsan
              echo 'implicit-unsigned-integer-truncation:util/bytevectorhash.cpp' >> test/sanitizer_suppressions/ubsan
              echo 'TEST_RUNNER_TIMEOUT_FACTOR=400' >> $GITHUB_ENV
          - name: 'fun ext i386'
            file-env: './ci/test/00_setup_env_native_asan.sh'
            task_adjustments: |
              sed -i 's/ubuntu:24.04/debian:unstable/g' $FILE_ENV
              sed -i '/export APT_LLVM_V=".."/d' $FILE_ENV
              sed -i 's/-${APT_LLVM_V}//g' $FILE_ENV
              sed -i '/NO_DEPENDS/d' $FILE_ENV
              echo 'export DEP_OPTS="build_CC=clang build_CXX=clang++ CC=clang CXX=clang++"' >> $FILE_ENV
              sed -i "s/-DCMAKE_CXX_FLAGS='/-DAPPEND_LDFLAGS='-latomic' -DCMAKE_CXX_FLAGS='/g" $FILE_ENV
              echo 'export CI_IMAGE_PLATFORM="linux/i386"' >> $FILE_ENV
              echo 'implicit-signed-integer-truncation:MillisToTimeval' >> test/sanitizer_suppressions/ubsan
              echo 'implicit-signed-integer-truncation:streams.cpp' >> test/sanitizer_suppressions/ubsan
              echo 'implicit-unsigned-integer-truncation:util/hasher.h' >> test/sanitizer_suppressions/ubsan
              echo 'implicit-unsigned-integer-truncation:util/hasher.cpp' >> test/sanitizer_suppressions/ubsan
              echo 'implicit-unsigned-integer-truncation:util/bytevectorhash.cpp' >> test/sanitizer_suppressions/ubsan
              echo 'leak:test_bitcoin-qt' >> test/sanitizer_suppressions/lsan
              echo 'TEST_RUNNER_TIMEOUT_FACTOR=400' >> $GITHUB_ENV
              echo 'TEST_RUNNER_EXTRA="--extended"' >> $FILE_ENV
          - name: 'valgrind ext'
            file-env: './ci/test/00_setup_env_native_valgrind.sh'
            task_adjustments: |
              sed -i 's/TEST_RUNNER_EXTRA="/TEST_RUNNER_EXTRA="--extended /g' $FILE_ENV
          - name: 'fuzz valgrind'
            file-env: './ci/test/00_setup_env_native_fuzz_with_valgrind.sh'
            task_adjustments: ''  # No adjustmen, not run upstream, see https://github.com/bitcoin/bitcoin/pull/
          - name: 'clang-min'
            file-env: './ci/test/00_setup_env_native_nowallet.sh'
            task_adjustments: |
              sed -i 's/NO_WALLET=1//g' $FILE_ENV
              sed -i 's/DENABLE_WALLET=OFF/DENABLE_WALLET=ON/g' $FILE_ENV
          - name: 'i686 ipc'
            file-env: './ci/test/00_setup_env_i686_no_ipc.sh'
            task_adjustments: |
              sed -i 's/NO_IPC=1//g' $FILE_ENV
              sed -i 's/DENABLE_IPC=OFF/DENABLE_IPC=ON/g' $FILE_ENV
          - name: 's390x ext_fun+fuzz'
            file-env: './ci/test/00_setup_env_s390x.sh'
            task_adjustments: |
              sed -i 's/dev-mode/dev-mode -DCMAKE_BUILD_TYPE=Debug/g' $FILE_ENV
              echo 'export RUN_FUZZ_TESTS=true' >> $FILE_ENV
              sed -i 's/TEST_RUNNER_EXTRA="/TEST_RUNNER_EXTRA="--extended /g' $FILE_ENV
            requires_qemu: true
            runner: runner_test_001


    steps:
      - *CHECKOUT_BC

      - name: Set up QEMU
        if: ${{ matrix.requires_qemu && matrix.runner == null }}
        uses: docker/setup-qemu-action@v3

      - name: Apply matrix adjustments
        if: ${{ matrix.task_adjustments != '' }}
        run: |
          ${{ matrix.task_adjustments }}
          git --no-pager diff -U55

      - name: Create git archive
        run: |
          git add --all
          git config user.name "ci"
          git config user.email "ci@users.noreply.github.com"
          git commit --allow-empty --message "CI: snapshot"
          git show
          git archive --format=tar --prefix=repo-archive/ --output=repo.tar HEAD
          tar -xf repo.tar

      - name: CI script
        run: |
          cd repo-archive
          ./ci/test_run_all.sh

  debian-bookworm:
    name: 'debian bookworm [system libs]'
    runs-on: ubuntu-latest
    timeout-minutes: 360
    container:
      image: debian:bookworm

    steps:
      - *CHECKOUT_BC

      - name: Install dependencies (apt)
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y \
            pkg-config ccache \
            build-essential cmake \
            python3 python3-zmq libzmq3-dev \
            libboost-dev libsqlite3-dev systemtap-sdt-dev \
            libcapnp-dev capnproto libqrencode-dev \
            qt6-tools-dev qt6-l10n-tools qt6-base-dev \
            g++-12 clang-19 llvm-19 libc++-19-dev libc++abi-19-dev mold

      - name: Generate buildsystem
        run: |
          cmake -B bld \
            --preset=dev-mode -DENABLE_IPC=OFF -DBUILD_GUI=OFF \
            -DCMAKE_C_COMPILER=clang-19 \
            -DCMAKE_CXX_COMPILER='clang++-19;-stdlib=libc++' \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DWITH_CCACHE=ON

      - *BLD

      - name: Run tests (ctest+functional)
        run: *TESTS_RUN

  ubuntu-22_04:
    name: 'Ubuntu 22.04 [system libs]'
    runs-on: ubuntu-latest
    timeout-minutes: 360
    container:
      image: ubuntu:22.04

    steps:
      - *CHECKOUT_BC

      - name: Install dependencies (apt)
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y \
            pkg-config ccache \
            build-essential cmake \
            python3 python3-zmq libzmq3-dev \
            libboost-dev libsqlite3-dev systemtap-sdt-dev \
            libcapnp-dev capnproto libqrencode-dev \
            qt6-tools-dev qt6-l10n-tools qt6-base-dev \
            g++-12 clang llvm libc++-dev libc++abi-dev mold

      - name: Generate buildsystem
        run: |
          cmake -B bld \
            --preset=dev-mode -DBUILD_GUI=OFF -DENABLE_IPC=OFF \
            -DCMAKE_C_COMPILER=gcc-12 \
            -DCMAKE_CXX_COMPILER=g++-12 \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DWITH_CCACHE=ON

      - *BLD

      - name: Run tests (ctest+functional)
        run: *TESTS_RUN

  opensuse-tumbleweed:
    name: 'OpenSUSE Tumbleweed [system libs]'
    runs-on: ubuntu-latest
    timeout-minutes: 360
    container:
      image: opensuse/tumbleweed

    steps:
      - *CHECKOUT_BC

      - name: Install dependencies (zypper)
        run: |
          zypper --non-interactive install -t pattern devel_basis
          zypper --non-interactive install e2fsprogs git pkg-config cmake python3 libboost_headers-devel gcc-c++ ccache zeromq-devel qt6-base-devel qt6-tools-devel qt6-linguist-devel qrencode-devel sqlite3-devel libcapnp-devel capnproto

      - name: Generate buildsystem
        run: |
          cmake -B bld \
            --preset=dev-mode \
            -DWITH_USDT=OFF \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DWITH_CCACHE=ON

      - *BLD

      - name: Run tests (ctest+functional)
        run: *TESTS_RUN

  alpine:
    name: 'Alpine [system libs]'
    runs-on: ubuntu-latest
    timeout-minutes: 360
    container:
      image: alpine:edge

    steps:
      - *CHECKOUT_BC

      - name: Install dependencies (apk)
        run: |
          apk --no-cache add e2fsprogs-extra cmake g++ gcc git make pkgconfig python3 boost-dev zeromq-dev qt6-qtbase-dev qt6-qttools-dev ccache libqrencode-dev capnproto-dev

      - name: Generate buildsystem
        run: |
          cmake -B bld \
            --preset=dev-mode \
            -DWITH_USDT=OFF \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DWITH_CCACHE=ON

      - *BLD

      - name: Run tests (ctest+functional)
        run: *TESTS_RUN

  archlinux:
    name: 'Arch Linux [system libs]'
    runs-on: ubuntu-latest
    timeout-minutes: 360
    container:
      image: archlinux:latest

    steps:
      - *CHECKOUT_BC

      - name: Install dependencies (pacman)
        run: |
          pacman --noconfirm -Syu e2fsprogs cmake git gcc make python3 boost zeromq ccache qt6 qrencode capnproto

      - name: Generate buildsystem
        run: |
          cmake -B bld \
            --preset=dev-mode \
            -DAPPEND_CXXFLAGS="-Wno-error=stringop-overflow" \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DWITH_CCACHE=ON

      - *BLD

      - name: Run tests (ctest+functional)
        run: *TESTS_RUN

  fedora:
    name: 'Fedora [system libs]'
    runs-on: ubuntu-latest
    timeout-minutes: 360
    container:
      image: fedora:rawhide

    steps:
      - *CHECKOUT_BC

      - name: Install dependencies (dnf)
        run: |
          dnf install -y e2fsprogs ccache gcc-c++ make cmake boost-devel python3 qt6-qtbase-devel qt6-qttools-devel sqlite-devel capnproto capnproto-devel qrencode-devel systemtap-sdt-devel zeromq-devel

      - name: Generate buildsystem
        run: |
          cmake -B bld \
            --preset=dev-mode \
            -DAPPEND_CXXFLAGS="-Wno-error=stringop-overflow" \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DWITH_CCACHE=ON

      - *BLD

      - name: Run tests (ctest+functional)
        run: *TESTS_RUN

  fedora-fuzz:
    name: 'Fedora fuzz, asan, system libs'
    runs-on: ubuntu-latest
    timeout-minutes: 360
    container:
      image: fedora:rawhide

    steps:
      - *CHECKOUT_BC

      - name: Install dependencies (dnf)
        run: |
          dnf install -y make cmake boost-devel sqlite-devel capnproto capnproto-devel python3 clang llvm git

      - name: Generate buildsystem (fuzz)
        run: |
          cmake -B bld \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DWITH_CCACHE=ON \
            -DBUILD_FOR_FUZZING=ON \
            -DSANITIZERS=fuzzer,address,integer,undefined,float-divide-by-zero \
            -DCMAKE_C_COMPILER="clang" \
            -DCMAKE_CXX_COMPILER="clang++"

      - *BLD

      - name: Run fuzz tests
        run: |
          git clone https://github.com/bitcoin-core/qa-assets --depth=1 ./qa-assets
          export LSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/lsan"
          export TSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/tsan:halt_on_error=1"
          export UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1"
          ./bld/test/fuzz/test_runner.py -j $(nproc) -l DEBUG ./qa-assets/fuzz_corpora/

  mac-cross-intel:
    name: 'Linux->macOS Intel cross, no tests'
    runs-on: ubuntu-latest
    if: ${{ vars.SKIP_BRANCH_PUSH != 'true' || github.event_name == 'pull_request' }}

    env:
      FILE_ENV: './ci/test/00_setup_env_mac_cross_intel.sh'
      DANGER_CI_ON_HOST_FOLDERS: 1

    steps:
      - *CHECKOUT_BC

      - name: Configure environment
        uses: bitcoin/bitcoin/.github/actions/configure-environment@master

      - name: Restore caches
        id: restore-cache
        uses: bitcoin/bitcoin/.github/actions/cache/restore@master

      - name: Configure Docker
        uses: bitcoin/bitcoin/.github/actions/configure-docker@master

      - name: CI script
        run: |
          ./ci/test_run_all.sh

      - name: Save caches
        uses: bitcoin/bitcoin/.github/actions/cache/save@master

      - name: Upload built executables
        uses: actions/upload-artifact@v4
        with:
          name: mac-cross-intel-executables-${{ github.run_id }}
          path: |
            ${{ env.BASE_BUILD_DIR }}/bin/*
            ${{ env.BASE_BUILD_DIR }}/src/secp256k1/bin/*
            ${{ env.BASE_BUILD_DIR }}/src/univalue/*
            ${{ env.BASE_BUILD_DIR }}/test/config.ini
            ${{ env.BASE_BUILD_DIR }}/lib/*.dylib

  mac-native-test-intel-rosetta-2:
    name: 'macOS, test cross-built Intel on Rosetta 2'
    runs-on: macos-26  # Last release with Intel support, but GHA only offers Rosetta 2
    needs: mac-cross-intel

    env:
      TEST_RUNNER_TIMEOUT_FACTOR: 40
      DYLD_LIBRARY_PATH: ${{ github.workspace }}/lib
      QT_STYLE_OVERRIDE: fusion

    steps:
      - *CHECKOUT_BC

      - name: Download built executables
        uses: actions/download-artifact@v4
        with:
          name: mac-cross-intel-executables-${{ github.run_id }}

      - name: Ensure downloaded binaries are executable
        run: chmod -R +x ./bin ./src/secp256k1/bin ./src/univalue

      - name: Run bitcoind
        run: ./bin/bitcoind -version

      - name: Run Qt unit tests
        run: ./bin/test_bitcoin-qt

      - name: Run unit tests
        run: |
          ./bin/test_bitcoin -l test_suite
          ./src/secp256k1/bin/exhaustive_tests
          ./src/secp256k1/bin/noverify_tests
          ./src/secp256k1/bin/tests
          ./src/univalue/object
          ./src/univalue/unitester

      - name: Adjust paths in test/config.ini
        run: |
          sed -i '' "s|^SRCDIR=.*|SRCDIR=${{ github.workspace }}|" test/config.ini
          sed -i '' "s|^BUILDDIR=.*|BUILDDIR=${{ github.workspace }}|" test/config.ini
          sed -i '' "s|^RPCAUTH=.*|RPCAUTH=${{ github.workspace }}/share/rpcauth/rpcauth.py|" test/config.ini
          cat test/config.ini

      - name: Set previous release directory
        run: |
          echo "PREVIOUS_RELEASES_DIR=${{ runner.temp }}/previous_releases" >> "$GITHUB_ENV"

      - name: Get previous releases
        run: ./test/get_previous_releases.py --target-dir $PREVIOUS_RELEASES_DIR

      - name: Run functional tests
        env:
          TEST_RUNNER_EXTRA: ${{ github.event_name != 'pull_request' && '--extended' || '' }}
        run: python3 test/functional/test_runner.py --jobs $(sysctl -n hw.ncpu) --quiet --tmpdirprefix="$RUNNER_TEMP" --combinedlogslen=99999999 --timeout-factor=$TEST_RUNNER_TIMEOUT_FACTOR $TEST_RUNNER_EXTRA

  mac-cross:
    name: 'Linux->macOS cross, no tests'
    runs-on: ubuntu-latest
    if: ${{ vars.SKIP_BRANCH_PUSH != 'true' || github.event_name == 'pull_request' }}

    env:
      FILE_ENV: './ci/test/00_setup_env_mac_cross.sh'
      DANGER_CI_ON_HOST_FOLDERS: 1

    steps:
      - *CHECKOUT_BC

      - name: Configure environment
        uses: bitcoin/bitcoin/.github/actions/configure-environment@master

      - name: Restore caches
        id: restore-cache
        uses: bitcoin/bitcoin/.github/actions/cache/restore@master

      - name: Configure Docker
        uses: bitcoin/bitcoin/.github/actions/configure-docker@master

      - name: CI script
        run: |
          ./ci/test_run_all.sh

      - name: Save caches
        uses: bitcoin/bitcoin/.github/actions/cache/save@master

      - name: Upload built executables
        uses: actions/upload-artifact@v4
        with:
          name: mac-cross-executables-${{ github.run_id }}
          path: |
            ${{ env.BASE_BUILD_DIR }}/bin/*
            ${{ env.BASE_BUILD_DIR }}/src/secp256k1/bin/*
            ${{ env.BASE_BUILD_DIR }}/src/univalue/*
            ${{ env.BASE_BUILD_DIR }}/test/config.ini
            ${{ env.BASE_BUILD_DIR }}/lib/*.dylib

  mac-native-test:
    name: 'macOS, test cross-built'
    # The minimum supported macos version for releases
    runs-on: macos-14
    needs: mac-cross

    env:
      TEST_RUNNER_TIMEOUT_FACTOR: 40
      DYLD_LIBRARY_PATH: ${{ github.workspace }}/lib
      QT_STYLE_OVERRIDE: fusion

    steps:
      - *CHECKOUT_BC

      - name: Download built executables
        uses: actions/download-artifact@v4
        with:
          name: mac-cross-executables-${{ github.run_id }}

      - name: Ensure downloaded binaries are executable
        run: chmod -R +x ./bin ./src/secp256k1/bin ./src/univalue

      - name: Run bitcoind
        run: ./bin/bitcoind -version

      - name: Run Qt unit tests
        run: ./bin/test_bitcoin-qt

      - name: Run unit tests
        run: |
          ./bin/test_bitcoin -l test_suite
          ./src/secp256k1/bin/exhaustive_tests
          ./src/secp256k1/bin/noverify_tests
          ./src/secp256k1/bin/tests
          ./src/univalue/object
          ./src/univalue/unitester

      - name: Adjust paths in test/config.ini
        run: |
          sed -i '' "s|^SRCDIR=.*|SRCDIR=${{ github.workspace }}|" test/config.ini
          sed -i '' "s|^BUILDDIR=.*|BUILDDIR=${{ github.workspace }}|" test/config.ini
          sed -i '' "s|^RPCAUTH=.*|RPCAUTH=${{ github.workspace }}/share/rpcauth/rpcauth.py|" test/config.ini
          cat test/config.ini

      - name: Set previous release directory
        run: |
          echo "PREVIOUS_RELEASES_DIR=${{ runner.temp }}/previous_releases" >> "$GITHUB_ENV"

      - name: Get previous releases
        run: ./test/get_previous_releases.py --target-dir $PREVIOUS_RELEASES_DIR

      - name: Run functional tests
        env:
          TEST_RUNNER_EXTRA: ${{ github.event_name != 'pull_request' && '--extended' || '' }}
        run: python3 test/functional/test_runner.py --jobs $(sysctl -n hw.ncpu) --quiet --tmpdirprefix="$RUNNER_TEMP" --combinedlogslen=99999999 --timeout-factor=$TEST_RUNNER_TIMEOUT_FACTOR $TEST_RUNNER_EXTRA
